module.exports = {
  ci: {
    collect: {
      url: [
        '/',
        '/404.html',
        '/explore/',
        '/close',
        '/confirm',
        '/offers',
        '/request',
        '/unsubscribe',
        '/win/',
      ],
      staticDistDir: './dist',
    },
    assert: {
      preset: 'lighthouse:recommended',
      assertions: {
        'unused-javascript': 'warn',
        'unused-css-rules': 'warn',
        'non-composited-animations': 'warn',
        'errors-in-console': 'warn',
        canonical: 'warn',
        'color-contrast': 'warn',
        'csp-xss': 'wanr',
        'html-lang-valid': 'warn',
        'link-text': 'warn',
        'maskable-icon': 'warn',
        'preload-lcp-image': 'warn',
        'uses-rel-preconnect': 'warn',
        'uses-responsive-images': 'warn',
        'unsized-images': 'warn',
        'font-size': 'warn',
        'image-alt': 'warn',
        'duplicate-id-active': 'warn',
        'link-name': 'warn',
        'font-display': 'warn',
        'external-anchors-use-rel-noopener': 'warn',
        'button-name': 'warn',
        'image-size-responsive': 'warn',
        'uses-optimized-images': 'warn',
        list: 'warn',
      },
    },
    upload: {
      target: 'temporary-public-storage',
    },
  },
};
